//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighCharts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignKPI
    {
        public long Id { get; set; }
        public Nullable<long> KPIId { get; set; }
        public string KPIName { get; set; }
        public string Target { get; set; }
        public string ScoreCardTypeId { get; set; }
        public string ScoreCardName { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string KpiOwner { get; set; }
        public string KpiOwnerEmpId { get; set; }
    }
}
