//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighCharts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignKPIDetail
    {
        public long Id { get; set; }
        public Nullable<long> AssignKPIId { get; set; }
        public string KPIName { get; set; }
        public string Target { get; set; }
        public string Actual { get; set; }
        public string PartialActual { get; set; }
        public string GlobalActual { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string ActualDateString { get; set; }
        public Nullable<bool> IsPartialApproved { get; set; }
        public string PartialApprovalComment { get; set; }
        public Nullable<System.DateTime> PartialApprovalDate { get; set; }
        public string PartiallyApprovedBy { get; set; }
        public Nullable<bool> IsGlobalApproved { get; set; }
        public string GlobalApprovalComment { get; set; }
        public Nullable<System.DateTime> GlobalApprovalDate { get; set; }
        public string GloballyApprovedBy { get; set; }
        public long AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
