//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighCharts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedKpiLog
    {
        public long Id { get; set; }
        public Nullable<long> AssignKpiId { get; set; }
        public Nullable<decimal> CurrentTarget { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> MonthNumber { get; set; }
        public Nullable<long> Year { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
