//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighCharts
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIUser
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string UserRole { get; set; }
        public bool Active { get; set; }
        public string Location { get; set; }
        public long AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
