//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighCharts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThreeSixtyAppraisal
    {
        public long ThreeSixtyAppraisalId { get; set; }
        public long AttributeTypeId { get; set; }
        public long AppraisalAttributeId { get; set; }
        public long BaseScoreId { get; set; }
        public int Scored { get; set; }
        public long AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
