//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighCharts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WKPIEntities1 : DbContext
    {
        public WKPIEntities1()
            : base("name=WKPIEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppraisalAttribute> AppraisalAttributes { get; set; }
        public virtual DbSet<AssignKPIDetail> AssignKPIDetails { get; set; }
        public virtual DbSet<AssignKPI> AssignKPIs { get; set; }
        public virtual DbSet<AttributeType> AttributeTypes { get; set; }
        public virtual DbSet<BaseScore> BaseScores { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<KPI> KPIs { get; set; }
        public virtual DbSet<KPIUser> KPIUsers { get; set; }
        public virtual DbSet<Objective> Objectives { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Perspective> Perspectives { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScoreCard> ScoreCards { get; set; }
        public virtual DbSet<ScoreCardDetail> ScoreCardDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThreeSixtyAppraisal> ThreeSixtyAppraisals { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<AssignedKpiLog> AssignedKpiLogs { get; set; }
    }
}
